apiVersion: v2
name: placement
description: Identity, coupon placement saga and bet history.
type: application
version: 0.1.0
appVersion: main
dependencies:
  - name: swiftbets-service
    version: 0.1.0
    repository: file://../swiftbets-service
